---

- hosts: all,!localhost
  remote_user: root
  gather_facts: true
  tasks:

    - name: Configure Interface on provisioning network
      copy:
         dest: "/etc/sysconfig/network-scripts/ifcfg-bond2"
         content: |
                DEVICE=bond2
                USERCTL=no
                BOOTPROTO=static
                TYPE=Ethernet
                BONDING_MASTER=yes
                BONDING_OPTS="mode=4 miimon=100 bond-lacp-rate=slow"
                NM_CONTROLLED=no
                BRIDGE=br2-bond2

    - name: Configure Bridge on provisoning network
      copy:
        dest: "/etc/sysconfig/network-scripts/ifcfg-br2-bond2"
        content: |
                DEVICE=br2-bond2
                TYPE=Bridge
                IPADDR={{ bond2_ip2 }}
                NETMASK=255.255.255.0
                ONBOOT=yes
                BOOTPROTO=none
                NM_CONTROLLED=no
                DELAY=0

